// ─────────────────────────────────────────────────────────────────────────────
// Master Task Library — seed data (baseline custom-home process template)
//
// This is the company's starting playbook for building a custom home, lead
// capture → warranty. It is intentionally easy to edit: add/remove/adjust
// entries here and re-run the seed (admin "Load baseline template" button on the
// Master Task Library page, or POST /api/taskLibrary/master/seed). Seeding is
// idempotent on `taskCode` — existing tasks are left untouched, new ones added.
//
// Keep enums in sync with shared/taskLibrary-types.ts (the functions build can't
// import from shared/). Only the authoring fields live here; the seeder fills
// the rest (version, timestamps, order, archivedAt, etc.).
// ─────────────────────────────────────────────────────────────────────────────

export type SeedTaskPhase =
  | 'Lead Capture & Qualification'
  | 'Preconstruction'
  | 'Procurement, Scheduling & Project Controls'
  | 'Site Prep & Foundation'
  | 'Framing & Dry-In'
  | 'MEP Rough, Inspections, Insulation & Drywall'
  | 'Finishes & Commissioning'
  | 'Punchlist, Closeout & Warranty';

export interface SeedMasterTask {
  taskCode: string;
  phase: SeedTaskPhase;
  title: string;
  description: string;
  recommendedRole: string;
  defaultAssigneeRole: string;
  defaultDurationDays: number;
  suggestedStartOffset: number;
  dependencies: string[];
  acceptanceCriteria: string[];
  requiredPhotos: number;
  requiredDocuments: string[];
  inspectionRequired: boolean;
  drawMilestoneRelevant: boolean;
  clientVisible: boolean;
  subcontractorVisible: boolean;
  isRequired: boolean;
  tags: string[];
  appliesWhen: string;
  riskLevel: 'low' | 'medium' | 'high';
  qualityGate: boolean;
}

export const MASTER_TASK_SEED: SeedMasterTask[] = [
  // ── Phase 1: Lead Capture & Qualification ─────────────────────────────────
  {
    taskCode: 'LEAD-010',
    phase: 'Lead Capture & Qualification',
    title: 'Capture and log new lead',
    description:
      'Record the inbound lead in Skyeline OS with contact info, source, and project location. Respond within 24 hours.',
    recommendedRole: 'gc',
    defaultAssigneeRole: 'gc',
    defaultDurationDays: 1,
    suggestedStartOffset: 0,
    dependencies: [],
    acceptanceCriteria: [
      'Contact name, phone, and email recorded',
      'Lead source captured',
      'Initial response sent within 24h',
    ],
    requiredPhotos: 0,
    requiredDocuments: [],
    inspectionRequired: false,
    drawMilestoneRelevant: false,
    clientVisible: false,
    subcontractorVisible: false,
    isRequired: true,
    tags: [],
    appliesWhen: 'Every new lead',
    riskLevel: 'low',
    qualityGate: false,
  },
  {
    taskCode: 'LEAD-020',
    phase: 'Lead Capture & Qualification',
    title: 'Qualify lead (budget, timeline, lot, financing)',
    description:
      'Discovery call to confirm budget range, desired timeline, lot status, and financing readiness. Decide go / no-go.',
    recommendedRole: 'gc',
    defaultAssigneeRole: 'gc',
    defaultDurationDays: 3,
    suggestedStartOffset: 1,
    dependencies: ['LEAD-010'],
    acceptanceCriteria: [
      'Budget range confirmed',
      'Lot ownership / status confirmed',
      'Financing readiness assessed',
      'Go / no-go decision recorded',
    ],
    requiredPhotos: 0,
    requiredDocuments: [],
    inspectionRequired: false,
    drawMilestoneRelevant: false,
    clientVisible: false,
    subcontractorVisible: false,
    isRequired: true,
    tags: [],
    appliesWhen: 'Every qualified lead',
    riskLevel: 'medium',
    qualityGate: false,
  },
  {
    taskCode: 'LEAD-030',
    phase: 'Lead Capture & Qualification',
    title: 'Site walk / lot feasibility review',
    description:
      'Visit the lot to assess access, slope, utilities, soils concerns, and obvious cost drivers before committing to a proposal.',
    recommendedRole: 'superintendent',
    defaultAssigneeRole: 'superintendent',
    defaultDurationDays: 2,
    suggestedStartOffset: 4,
    dependencies: ['LEAD-020'],
    acceptanceCriteria: [
      'Site access and staging assessed',
      'Utility availability noted (power, water, sewer/septic)',
      'Slope / excavation risk flagged',
      'Site photos uploaded',
    ],
    requiredPhotos: 6,
    requiredDocuments: [],
    inspectionRequired: false,
    drawMilestoneRelevant: false,
    clientVisible: false,
    subcontractorVisible: false,
    isRequired: true,
    tags: ['hillside', 'complex excavation', 'septic', 'well'],
    appliesWhen: 'Every project with a known lot',
    riskLevel: 'high',
    qualityGate: false,
  },
  {
    taskCode: 'LEAD-040',
    phase: 'Lead Capture & Qualification',
    title: 'Sign preconstruction / design agreement',
    description:
      'Execute the preconstruction services agreement and collect the initial deposit before design work begins.',
    recommendedRole: 'gc',
    defaultAssigneeRole: 'gc',
    defaultDurationDays: 5,
    suggestedStartOffset: 6,
    dependencies: ['LEAD-030'],
    acceptanceCriteria: [
      'Agreement signed by client',
      'Initial deposit received',
    ],
    requiredPhotos: 0,
    requiredDocuments: ['Signed preconstruction agreement'],
    inspectionRequired: false,
    drawMilestoneRelevant: true,
    clientVisible: true,
    subcontractorVisible: false,
    isRequired: true,
    tags: [],
    appliesWhen: 'Before any design/estimate work',
    riskLevel: 'medium',
    qualityGate: true,
  },

  // ── Phase 2: Preconstruction ──────────────────────────────────────────────
  {
    taskCode: 'PRE-010',
    phase: 'Preconstruction',
    title: 'Architectural design & plan development',
    description:
      'Develop schematic through construction drawings with the architect/designer. Iterate with client on layout and scope.',
    recommendedRole: 'designer',
    defaultAssigneeRole: 'designer',
    defaultDurationDays: 45,
    suggestedStartOffset: 0,
    dependencies: ['LEAD-040'],
    acceptanceCriteria: [
      'Client-approved floor plans',
      'Elevations finalized',
      'Construction drawing set issued',
    ],
    requiredPhotos: 0,
    requiredDocuments: ['Construction drawing set (PDF)'],
    inspectionRequired: false,
    drawMilestoneRelevant: false,
    clientVisible: true,
    subcontractorVisible: false,
    isRequired: true,
    tags: ['luxury finishes'],
    appliesWhen: 'Every custom home',
    riskLevel: 'high',
    qualityGate: true,
  },
  {
    taskCode: 'PRE-020',
    phase: 'Preconstruction',
    title: 'Structural engineering',
    description:
      'Engage structural engineer for foundation and framing design, including any special conditions (hillside, retaining, snow load).',
    recommendedRole: 'vendor',
    defaultAssigneeRole: 'vendor',
    defaultDurationDays: 21,
    suggestedStartOffset: 30,
    dependencies: ['PRE-010'],
    acceptanceCriteria: [
      'Stamped structural drawings received',
      'Special conditions addressed (hillside/retaining/snow)',
    ],
    requiredPhotos: 0,
    requiredDocuments: ['Stamped structural plans'],
    inspectionRequired: false,
    drawMilestoneRelevant: false,
    clientVisible: false,
    subcontractorVisible: false,
    isRequired: true,
    tags: ['hillside', 'retaining wall', 'snow load', 'basement'],
    appliesWhen: 'Every custom home',
    riskLevel: 'high',
    qualityGate: true,
  },
  {
    taskCode: 'PRE-030',
    phase: 'Preconstruction',
    title: 'Geotechnical / soils report',
    description:
      'Order soils investigation to inform foundation design. Critical on hillside, expansive soils, or high water table sites.',
    recommendedRole: 'vendor',
    defaultAssigneeRole: 'vendor',
    defaultDurationDays: 14,
    suggestedStartOffset: 5,
    dependencies: ['LEAD-040'],
    acceptanceCriteria: ['Geotech report received', 'Foundation recommendations incorporated'],
    requiredPhotos: 0,
    requiredDocuments: ['Geotechnical report'],
    inspectionRequired: false,
    drawMilestoneRelevant: false,
    clientVisible: false,
    subcontractorVisible: false,
    isRequired: false,
    tags: ['hillside', 'complex excavation', 'basement'],
    appliesWhen: 'Hillside, expansive soils, or basement sites',
    riskLevel: 'high',
    qualityGate: false,
  },
  {
    taskCode: 'PRE-040',
    phase: 'Preconstruction',
    title: 'Detailed estimate & budget',
    description:
      'Build the cost-plus estimate from the construction set. Owner Price + Contractor Fee = Total Cost. Review with client.',
    recommendedRole: 'estimator',
    defaultAssigneeRole: 'estimator',
    defaultDurationDays: 14,
    suggestedStartOffset: 40,
    dependencies: ['PRE-010'],
    acceptanceCriteria: [
      'All scopes line-itemed',
      'Allowances documented',
      'Client budget review completed',
    ],
    requiredPhotos: 0,
    requiredDocuments: ['Estimate / budget export'],
    inspectionRequired: false,
    drawMilestoneRelevant: true,
    clientVisible: true,
    subcontractorVisible: false,
    isRequired: true,
    tags: [],
    appliesWhen: 'Every custom home',
    riskLevel: 'high',
    qualityGate: true,
  },
  {
    taskCode: 'PRE-050',
    phase: 'Preconstruction',
    title: 'Permit submittal & approval',
    description:
      'Submit construction documents to the jurisdiction (and HOA/ARC if applicable). Track plan-check comments to approval.',
    recommendedRole: 'projectManager',
    defaultAssigneeRole: 'projectManager',
    defaultDurationDays: 45,
    suggestedStartOffset: 55,
    dependencies: ['PRE-020', 'PRE-040'],
    acceptanceCriteria: [
      'Permit application submitted',
      'Plan-check comments resolved',
      'Building permit issued',
    ],
    requiredPhotos: 0,
    requiredDocuments: ['Issued building permit'],
    inspectionRequired: false,
    drawMilestoneRelevant: false,
    clientVisible: true,
    subcontractorVisible: false,
    isRequired: true,
    tags: ['HOA'],
    appliesWhen: 'Every custom home',
    riskLevel: 'high',
    qualityGate: true,
  },
  {
    taskCode: 'PRE-060',
    phase: 'Preconstruction',
    title: 'HOA / ARC approval',
    description:
      'Obtain architectural review committee approval for exterior design, materials, and colors per HOA covenants.',
    recommendedRole: 'projectManager',
    defaultAssigneeRole: 'projectManager',
    defaultDurationDays: 30,
    suggestedStartOffset: 45,
    dependencies: ['PRE-010'],
    acceptanceCriteria: ['ARC submittal complete', 'Written HOA approval received'],
    requiredPhotos: 0,
    requiredDocuments: ['HOA/ARC approval letter'],
    inspectionRequired: false,
    drawMilestoneRelevant: false,
    clientVisible: true,
    subcontractorVisible: false,
    isRequired: false,
    tags: ['HOA'],
    appliesWhen: 'Lots within an HOA',
    riskLevel: 'medium',
    qualityGate: false,
  },
  {
    taskCode: 'PRE-070',
    phase: 'Preconstruction',
    title: 'Construction contract & financing close',
    description:
      'Execute the construction agreement and confirm construction loan / financing is closed and funded before mobilizing.',
    recommendedRole: 'gc',
    defaultAssigneeRole: 'gc',
    defaultDurationDays: 14,
    suggestedStartOffset: 60,
    dependencies: ['PRE-040'],
    acceptanceCriteria: [
      'Construction contract signed',
      'Financing closed / funds confirmed',
    ],
    requiredPhotos: 0,
    requiredDocuments: ['Signed construction contract'],
    inspectionRequired: false,
    drawMilestoneRelevant: true,
    clientVisible: true,
    subcontractorVisible: false,
    isRequired: true,
    tags: [],
    appliesWhen: 'Every custom home',
    riskLevel: 'high',
    qualityGate: true,
  },

  // ── Phase 3: Procurement, Scheduling & Project Controls ───────────────────
  {
    taskCode: 'PROC-010',
    phase: 'Procurement, Scheduling & Project Controls',
    title: 'Build baseline construction schedule',
    description:
      'Create the master Gantt schedule with phases, milestones, and subcontractor sequencing from permit issuance to closeout.',
    recommendedRole: 'projectManager',
    defaultAssigneeRole: 'projectManager',
    defaultDurationDays: 5,
    suggestedStartOffset: 0,
    dependencies: ['PRE-070'],
    acceptanceCriteria: [
      'All phases sequenced',
      'Key milestones dated',
      'Critical path identified',
    ],
    requiredPhotos: 0,
    requiredDocuments: ['Baseline schedule'],
    inspectionRequired: false,
    drawMilestoneRelevant: false,
    clientVisible: true,
    subcontractorVisible: false,
    isRequired: true,
    tags: [],
    appliesWhen: 'Every custom home',
    riskLevel: 'medium',
    qualityGate: false,
  },
  {
    taskCode: 'PROC-020',
    phase: 'Procurement, Scheduling & Project Controls',
    title: 'Issue bid packages to subcontractors',
    description:
      'Send trade bid packages, collect and level bids, and award subcontracts for each scope.',
    recommendedRole: 'estimator',
    defaultAssigneeRole: 'estimator',
    defaultDurationDays: 21,
    suggestedStartOffset: 2,
    dependencies: ['PRE-040'],
    acceptanceCriteria: [
      'Bid packages sent for all trades',
      'Bids leveled',
      'Subcontracts awarded',
    ],
    requiredPhotos: 0,
    requiredDocuments: ['Awarded subcontracts'],
    inspectionRequired: false,
    drawMilestoneRelevant: false,
    clientVisible: false,
    subcontractorVisible: true,
    isRequired: true,
    tags: [],
    appliesWhen: 'Every custom home',
    riskLevel: 'medium',
    qualityGate: false,
  },
  {
    taskCode: 'PROC-030',
    phase: 'Procurement, Scheduling & Project Controls',
    title: 'Order long-lead items',
    description:
      'Identify and order long-lead materials early — custom windows, appliances, elevator, specialty roofing — to protect the schedule.',
    recommendedRole: 'projectManager',
    defaultAssigneeRole: 'projectManager',
    defaultDurationDays: 7,
    suggestedStartOffset: 3,
    dependencies: ['PRE-040'],
    acceptanceCriteria: [
      'Long-lead list compiled',
      'POs issued',
      'Delivery dates confirmed against schedule',
    ],
    requiredPhotos: 0,
    requiredDocuments: ['Purchase orders'],
    inspectionRequired: false,
    drawMilestoneRelevant: false,
    clientVisible: false,
    subcontractorVisible: false,
    isRequired: true,
    tags: ['long-lead custom windows', 'elevator', 'luxury finishes'],
    appliesWhen: 'Projects with long-lead materials',
    riskLevel: 'high',
    qualityGate: false,
  },
  {
    taskCode: 'PROC-040',
    phase: 'Procurement, Scheduling & Project Controls',
    title: 'Collect subcontractor insurance & compliance',
    description:
      'Verify COIs, licenses, and W-9s for all awarded subcontractors before they mobilize on site.',
    recommendedRole: 'projectManager',
    defaultAssigneeRole: 'projectManager',
    defaultDurationDays: 7,
    suggestedStartOffset: 14,
    dependencies: ['PROC-020'],
    acceptanceCriteria: [
      'Current COI on file for each sub',
      'Licenses verified',
      'W-9s collected',
    ],
    requiredPhotos: 0,
    requiredDocuments: ['Certificates of insurance'],
    inspectionRequired: false,
    drawMilestoneRelevant: false,
    clientVisible: false,
    subcontractorVisible: true,
    isRequired: true,
    tags: [],
    appliesWhen: 'Every custom home',
    riskLevel: 'medium',
    qualityGate: true,
  },
  {
    taskCode: 'PROC-050',
    phase: 'Procurement, Scheduling & Project Controls',
    title: 'Set up draw schedule',
    description:
      'Establish the lender/client draw schedule mapped to construction milestones for billing throughout the project.',
    recommendedRole: 'gc',
    defaultAssigneeRole: 'gc',
    defaultDurationDays: 3,
    suggestedStartOffset: 1,
    dependencies: ['PRE-070'],
    acceptanceCriteria: ['Draw milestones defined', 'Lender draw schedule approved'],
    requiredPhotos: 0,
    requiredDocuments: ['Draw schedule'],
    inspectionRequired: false,
    drawMilestoneRelevant: true,
    clientVisible: true,
    subcontractorVisible: false,
    isRequired: true,
    tags: [],
    appliesWhen: 'Financed projects',
    riskLevel: 'medium',
    qualityGate: false,
  },

  // ── Phase 4: Site Prep & Foundation ───────────────────────────────────────
  {
    taskCode: 'SITE-010',
    phase: 'Site Prep & Foundation',
    title: 'Site mobilization & temporary services',
    description:
      'Set up site fencing, temp power, temp toilet, dumpster, erosion control (SWPPP), and construction access.',
    recommendedRole: 'superintendent',
    defaultAssigneeRole: 'superintendent',
    defaultDurationDays: 3,
    suggestedStartOffset: 0,
    dependencies: ['PRE-050'],
    acceptanceCriteria: [
      'Erosion control installed',
      'Temp power/water/toilet on site',
      'Site secured',
    ],
    requiredPhotos: 4,
    requiredDocuments: [],
    inspectionRequired: false,
    drawMilestoneRelevant: true,
    clientVisible: true,
    subcontractorVisible: true,
    isRequired: true,
    tags: [],
    appliesWhen: 'Every custom home',
    riskLevel: 'medium',
    qualityGate: false,
  },
  {
    taskCode: 'SITE-020',
    phase: 'Site Prep & Foundation',
    title: 'Excavation & rough grading',
    description:
      'Clear, excavate, and rough-grade the building pad. Handle special excavation, shoring, and retaining as engineered.',
    recommendedRole: 'subcontractor',
    defaultAssigneeRole: 'subcontractor',
    defaultDurationDays: 7,
    suggestedStartOffset: 3,
    dependencies: ['SITE-010'],
    acceptanceCriteria: [
      'Pad excavated to engineered elevation',
      'Over-dig / shoring per geotech',
      'Spoils managed',
    ],
    requiredPhotos: 6,
    requiredDocuments: [],
    inspectionRequired: false,
    drawMilestoneRelevant: true,
    clientVisible: true,
    subcontractorVisible: true,
    isRequired: true,
    tags: ['hillside', 'complex excavation', 'basement', 'retaining wall'],
    appliesWhen: 'Every custom home',
    riskLevel: 'high',
    qualityGate: false,
  },
  {
    taskCode: 'SITE-030',
    phase: 'Site Prep & Foundation',
    title: 'Footings — form, rebar & inspection',
    description:
      'Form and set rebar for footings; pass footing/rebar inspection before placing concrete.',
    recommendedRole: 'subcontractor',
    defaultAssigneeRole: 'subcontractor',
    defaultDurationDays: 5,
    suggestedStartOffset: 10,
    dependencies: ['SITE-020'],
    acceptanceCriteria: [
      'Footings formed to plan',
      'Rebar per structural drawings',
      'Footing inspection passed',
    ],
    requiredPhotos: 4,
    requiredDocuments: [],
    inspectionRequired: true,
    drawMilestoneRelevant: true,
    clientVisible: false,
    subcontractorVisible: true,
    isRequired: true,
    tags: [],
    appliesWhen: 'Every custom home',
    riskLevel: 'high',
    qualityGate: true,
  },
  {
    taskCode: 'SITE-040',
    phase: 'Site Prep & Foundation',
    title: 'Foundation walls / slab & waterproofing',
    description:
      'Place foundation walls or slab, then damp-proof/waterproof and install foundation drainage before backfill.',
    recommendedRole: 'subcontractor',
    defaultAssigneeRole: 'subcontractor',
    defaultDurationDays: 10,
    suggestedStartOffset: 15,
    dependencies: ['SITE-030'],
    acceptanceCriteria: [
      'Foundation poured to plan',
      'Waterproofing applied',
      'Perimeter drain installed',
      'Foundation inspection passed',
    ],
    requiredPhotos: 6,
    requiredDocuments: [],
    inspectionRequired: true,
    drawMilestoneRelevant: true,
    clientVisible: true,
    subcontractorVisible: true,
    isRequired: true,
    tags: ['basement'],
    appliesWhen: 'Every custom home',
    riskLevel: 'high',
    qualityGate: true,
  },
  {
    taskCode: 'SITE-050',
    phase: 'Site Prep & Foundation',
    title: 'Under-slab plumbing & backfill',
    description:
      'Rough in under-slab plumbing, inspect, then backfill and compact around the foundation.',
    recommendedRole: 'subcontractor',
    defaultAssigneeRole: 'subcontractor',
    defaultDurationDays: 6,
    suggestedStartOffset: 22,
    dependencies: ['SITE-040'],
    acceptanceCriteria: [
      'Under-slab plumbing inspected',
      'Backfill compacted in lifts',
    ],
    requiredPhotos: 3,
    requiredDocuments: [],
    inspectionRequired: true,
    drawMilestoneRelevant: false,
    clientVisible: false,
    subcontractorVisible: true,
    isRequired: true,
    tags: [],
    appliesWhen: 'Every custom home',
    riskLevel: 'medium',
    qualityGate: false,
  },
  {
    taskCode: 'SITE-060',
    phase: 'Site Prep & Foundation',
    title: 'Septic system installation',
    description:
      'Install and inspect the on-site septic system per the approved design where no public sewer exists.',
    recommendedRole: 'subcontractor',
    defaultAssigneeRole: 'subcontractor',
    defaultDurationDays: 7,
    suggestedStartOffset: 22,
    dependencies: ['SITE-020'],
    acceptanceCriteria: ['Septic installed per design', 'Health dept inspection passed'],
    requiredPhotos: 4,
    requiredDocuments: ['Septic permit / approval'],
    inspectionRequired: true,
    drawMilestoneRelevant: false,
    clientVisible: false,
    subcontractorVisible: true,
    isRequired: false,
    tags: ['septic'],
    appliesWhen: 'Sites without public sewer',
    riskLevel: 'high',
    qualityGate: true,
  },
  {
    taskCode: 'SITE-070',
    phase: 'Site Prep & Foundation',
    title: 'Well drilling & pump',
    description:
      'Drill the water well, install pump and pressure system, and verify potable water where no public water exists.',
    recommendedRole: 'subcontractor',
    defaultAssigneeRole: 'subcontractor',
    defaultDurationDays: 10,
    suggestedStartOffset: 5,
    dependencies: ['SITE-010'],
    acceptanceCriteria: ['Well drilled & flow verified', 'Potable water test passed'],
    requiredPhotos: 3,
    requiredDocuments: ['Well log', 'Water potability test'],
    inspectionRequired: false,
    drawMilestoneRelevant: false,
    clientVisible: false,
    subcontractorVisible: true,
    isRequired: false,
    tags: ['well'],
    appliesWhen: 'Sites without public water',
    riskLevel: 'high',
    qualityGate: true,
  },

  // ── Phase 5: Framing & Dry-In ─────────────────────────────────────────────
  {
    taskCode: 'FRAME-010',
    phase: 'Framing & Dry-In',
    title: 'Floor system & framing',
    description:
      'Frame floor systems, walls, and roof structure per the structural drawings.',
    recommendedRole: 'subcontractor',
    defaultAssigneeRole: 'subcontractor',
    defaultDurationDays: 21,
    suggestedStartOffset: 0,
    dependencies: ['SITE-050'],
    acceptanceCriteria: [
      'Framing complete to plan',
      'Hardware/straps installed per structural',
      'Square / plumb / level verified',
    ],
    requiredPhotos: 8,
    requiredDocuments: [],
    inspectionRequired: false,
    drawMilestoneRelevant: true,
    clientVisible: true,
    subcontractorVisible: true,
    isRequired: true,
    tags: ['snow load'],
    appliesWhen: 'Every custom home',
    riskLevel: 'high',
    qualityGate: true,
  },
  {
    taskCode: 'FRAME-020',
    phase: 'Framing & Dry-In',
    title: 'Roof dry-in (sheathing & underlayment)',
    description:
      'Sheath and dry-in the roof to protect the structure from weather before exterior trades.',
    recommendedRole: 'subcontractor',
    defaultAssigneeRole: 'subcontractor',
    defaultDurationDays: 5,
    suggestedStartOffset: 18,
    dependencies: ['FRAME-010'],
    acceptanceCriteria: ['Roof sheathed', 'Underlayment / ice-and-water installed', 'Structure weather-tight'],
    requiredPhotos: 4,
    requiredDocuments: [],
    inspectionRequired: false,
    drawMilestoneRelevant: true,
    clientVisible: true,
    subcontractorVisible: true,
    isRequired: true,
    tags: ['snow load'],
    appliesWhen: 'Every custom home',
    riskLevel: 'medium',
    qualityGate: false,
  },
  {
    taskCode: 'FRAME-030',
    phase: 'Framing & Dry-In',
    title: 'Windows & exterior doors',
    description:
      'Install windows and exterior doors, including flashing and air-sealing. Coordinate long-lead custom units.',
    recommendedRole: 'subcontractor',
    defaultAssigneeRole: 'subcontractor',
    defaultDurationDays: 7,
    suggestedStartOffset: 21,
    dependencies: ['FRAME-020'],
    acceptanceCriteria: ['Windows/doors set & flashed', 'Air sealing complete', 'Operation verified'],
    requiredPhotos: 5,
    requiredDocuments: [],
    inspectionRequired: false,
    drawMilestoneRelevant: false,
    clientVisible: true,
    subcontractorVisible: true,
    isRequired: true,
    tags: ['long-lead custom windows'],
    appliesWhen: 'Every custom home',
    riskLevel: 'medium',
    qualityGate: false,
  },
  {
    taskCode: 'FRAME-040',
    phase: 'Framing & Dry-In',
    title: 'Framing inspection',
    description:
      'Pass the rough framing inspection (often combined with sheathing/shear inspection).',
    recommendedRole: 'inspector',
    defaultAssigneeRole: 'superintendent',
    defaultDurationDays: 2,
    suggestedStartOffset: 22,
    dependencies: ['FRAME-030'],
    acceptanceCriteria: ['Framing inspection passed', 'Corrections (if any) completed'],
    requiredPhotos: 2,
    requiredDocuments: [],
    inspectionRequired: true,
    drawMilestoneRelevant: true,
    clientVisible: false,
    subcontractorVisible: true,
    isRequired: true,
    tags: [],
    appliesWhen: 'Every custom home',
    riskLevel: 'high',
    qualityGate: true,
  },

  // ── Phase 6: MEP Rough, Inspections, Insulation & Drywall ─────────────────
  {
    taskCode: 'MEP-010',
    phase: 'MEP Rough, Inspections, Insulation & Drywall',
    title: 'Plumbing rough-in',
    description: 'Rough-in supply and DWV plumbing throughout the home.',
    recommendedRole: 'subcontractor',
    defaultAssigneeRole: 'subcontractor',
    defaultDurationDays: 10,
    suggestedStartOffset: 0,
    dependencies: ['FRAME-040'],
    acceptanceCriteria: ['Supply & DWV roughed', 'Pressure test held'],
    requiredPhotos: 4,
    requiredDocuments: [],
    inspectionRequired: true,
    drawMilestoneRelevant: false,
    clientVisible: false,
    subcontractorVisible: true,
    isRequired: true,
    tags: [],
    appliesWhen: 'Every custom home',
    riskLevel: 'medium',
    qualityGate: false,
  },
  {
    taskCode: 'MEP-020',
    phase: 'MEP Rough, Inspections, Insulation & Drywall',
    title: 'HVAC rough-in',
    description: 'Install ductwork, line sets, and equipment locations; rough-in HVAC systems.',
    recommendedRole: 'subcontractor',
    defaultAssigneeRole: 'subcontractor',
    defaultDurationDays: 8,
    suggestedStartOffset: 3,
    dependencies: ['FRAME-040'],
    acceptanceCriteria: ['Ductwork installed', 'Equipment set/located', 'Combustion air provided'],
    requiredPhotos: 3,
    requiredDocuments: [],
    inspectionRequired: true,
    drawMilestoneRelevant: false,
    clientVisible: false,
    subcontractorVisible: true,
    isRequired: true,
    tags: [],
    appliesWhen: 'Every custom home',
    riskLevel: 'medium',
    qualityGate: false,
  },
  {
    taskCode: 'MEP-030',
    phase: 'MEP Rough, Inspections, Insulation & Drywall',
    title: 'Electrical rough-in',
    description:
      'Rough-in panels, wiring, boxes, and low-voltage/smart-home prewire.',
    recommendedRole: 'subcontractor',
    defaultAssigneeRole: 'subcontractor',
    defaultDurationDays: 10,
    suggestedStartOffset: 5,
    dependencies: ['FRAME-040'],
    acceptanceCriteria: ['Panel & circuits roughed', 'Boxes set', 'Low-voltage prewire complete'],
    requiredPhotos: 4,
    requiredDocuments: [],
    inspectionRequired: true,
    drawMilestoneRelevant: false,
    clientVisible: false,
    subcontractorVisible: true,
    isRequired: true,
    tags: ['smart home', 'solar', 'elevator'],
    appliesWhen: 'Every custom home',
    riskLevel: 'medium',
    qualityGate: false,
  },
  {
    taskCode: 'MEP-040',
    phase: 'MEP Rough, Inspections, Insulation & Drywall',
    title: 'Rough MEP inspections',
    description:
      'Pass plumbing, mechanical, and electrical rough inspections (and fire-sprinkler rough where applicable).',
    recommendedRole: 'inspector',
    defaultAssigneeRole: 'superintendent',
    defaultDurationDays: 3,
    suggestedStartOffset: 12,
    dependencies: ['MEP-010', 'MEP-020', 'MEP-030'],
    acceptanceCriteria: ['Plumbing rough passed', 'Mechanical rough passed', 'Electrical rough passed'],
    requiredPhotos: 2,
    requiredDocuments: [],
    inspectionRequired: true,
    drawMilestoneRelevant: true,
    clientVisible: false,
    subcontractorVisible: true,
    isRequired: true,
    tags: ['fire sprinklers'],
    appliesWhen: 'Every custom home',
    riskLevel: 'high',
    qualityGate: true,
  },
  {
    taskCode: 'MEP-050',
    phase: 'MEP Rough, Inspections, Insulation & Drywall',
    title: 'Insulation & inspection',
    description:
      'Install insulation and air sealing; pass insulation/energy inspection before drywall.',
    recommendedRole: 'subcontractor',
    defaultAssigneeRole: 'subcontractor',
    defaultDurationDays: 5,
    suggestedStartOffset: 16,
    dependencies: ['MEP-040'],
    acceptanceCriteria: ['Insulation installed to spec R-values', 'Air sealing complete', 'Insulation inspection passed'],
    requiredPhotos: 3,
    requiredDocuments: [],
    inspectionRequired: true,
    drawMilestoneRelevant: false,
    clientVisible: false,
    subcontractorVisible: true,
    isRequired: true,
    tags: ['snow load'],
    appliesWhen: 'Every custom home',
    riskLevel: 'medium',
    qualityGate: true,
  },
  {
    taskCode: 'MEP-060',
    phase: 'MEP Rough, Inspections, Insulation & Drywall',
    title: 'Drywall hang, finish & texture',
    description: 'Hang, tape, finish, and texture drywall throughout.',
    recommendedRole: 'subcontractor',
    defaultAssigneeRole: 'subcontractor',
    defaultDurationDays: 14,
    suggestedStartOffset: 20,
    dependencies: ['MEP-050'],
    acceptanceCriteria: ['Drywall hung', 'Finished to level spec', 'Texture approved'],
    requiredPhotos: 4,
    requiredDocuments: [],
    inspectionRequired: false,
    drawMilestoneRelevant: true,
    clientVisible: true,
    subcontractorVisible: true,
    isRequired: true,
    tags: [],
    appliesWhen: 'Every custom home',
    riskLevel: 'medium',
    qualityGate: false,
  },

  // ── Phase 7: Finishes & Commissioning ─────────────────────────────────────
  {
    taskCode: 'FIN-010',
    phase: 'Finishes & Commissioning',
    title: 'Interior trim, doors & millwork',
    description:
      'Install interior doors, base/case trim, stair parts, and custom millwork.',
    recommendedRole: 'subcontractor',
    defaultAssigneeRole: 'subcontractor',
    defaultDurationDays: 14,
    suggestedStartOffset: 0,
    dependencies: ['MEP-060'],
    acceptanceCriteria: ['Doors hung & operating', 'Trim installed', 'Millwork installed to spec'],
    requiredPhotos: 4,
    requiredDocuments: [],
    inspectionRequired: false,
    drawMilestoneRelevant: false,
    clientVisible: true,
    subcontractorVisible: true,
    isRequired: true,
    tags: ['luxury finishes'],
    appliesWhen: 'Every custom home',
    riskLevel: 'medium',
    qualityGate: false,
  },
  {
    taskCode: 'FIN-020',
    phase: 'Finishes & Commissioning',
    title: 'Cabinets & countertops',
    description:
      'Install cabinetry, then template and install countertops once cabinets are set.',
    recommendedRole: 'subcontractor',
    defaultAssigneeRole: 'subcontractor',
    defaultDurationDays: 12,
    suggestedStartOffset: 10,
    dependencies: ['FIN-010'],
    acceptanceCriteria: ['Cabinets set & leveled', 'Countertops templated & installed', 'Client selections matched'],
    requiredPhotos: 4,
    requiredDocuments: [],
    inspectionRequired: false,
    drawMilestoneRelevant: true,
    clientVisible: true,
    subcontractorVisible: true,
    isRequired: true,
    tags: ['luxury finishes'],
    appliesWhen: 'Every custom home',
    riskLevel: 'medium',
    qualityGate: false,
  },
  {
    taskCode: 'FIN-030',
    phase: 'Finishes & Commissioning',
    title: 'Flooring',
    description: 'Install all flooring — hardwood, tile, carpet — per client selections.',
    recommendedRole: 'subcontractor',
    defaultAssigneeRole: 'subcontractor',
    defaultDurationDays: 12,
    suggestedStartOffset: 14,
    dependencies: ['FIN-010'],
    acceptanceCriteria: ['Flooring installed per selections', 'Transitions complete', 'Protected for remaining work'],
    requiredPhotos: 4,
    requiredDocuments: [],
    inspectionRequired: false,
    drawMilestoneRelevant: false,
    clientVisible: true,
    subcontractorVisible: true,
    isRequired: true,
    tags: ['luxury finishes'],
    appliesWhen: 'Every custom home',
    riskLevel: 'medium',
    qualityGate: false,
  },
  {
    taskCode: 'FIN-040',
    phase: 'Finishes & Commissioning',
    title: 'Interior & exterior paint',
    description: 'Prime and finish-paint interior and exterior surfaces.',
    recommendedRole: 'subcontractor',
    defaultAssigneeRole: 'subcontractor',
    defaultDurationDays: 14,
    suggestedStartOffset: 5,
    dependencies: ['MEP-060'],
    acceptanceCriteria: ['Interior painted to spec', 'Exterior painted/sealed', 'Touch-ups complete'],
    requiredPhotos: 3,
    requiredDocuments: [],
    inspectionRequired: false,
    drawMilestoneRelevant: false,
    clientVisible: true,
    subcontractorVisible: true,
    isRequired: true,
    tags: [],
    appliesWhen: 'Every custom home',
    riskLevel: 'low',
    qualityGate: false,
  },
  {
    taskCode: 'FIN-050',
    phase: 'Finishes & Commissioning',
    title: 'MEP trim-out & fixtures',
    description:
      'Set plumbing fixtures, electrical devices/lighting, and HVAC registers/thermostats.',
    recommendedRole: 'subcontractor',
    defaultAssigneeRole: 'subcontractor',
    defaultDurationDays: 10,
    suggestedStartOffset: 22,
    dependencies: ['FIN-030'],
    acceptanceCriteria: ['Plumbing fixtures set & tested', 'Devices/lighting installed', 'HVAC trim complete'],
    requiredPhotos: 4,
    requiredDocuments: [],
    inspectionRequired: false,
    drawMilestoneRelevant: false,
    clientVisible: true,
    subcontractorVisible: true,
    isRequired: true,
    tags: ['smart home'],
    appliesWhen: 'Every custom home',
    riskLevel: 'medium',
    qualityGate: false,
  },
  {
    taskCode: 'FIN-060',
    phase: 'Finishes & Commissioning',
    title: 'Final grade, hardscape & landscaping',
    description:
      'Final site grade, driveway, hardscape, retaining, and landscaping per the site plan.',
    recommendedRole: 'subcontractor',
    defaultAssigneeRole: 'subcontractor',
    defaultDurationDays: 14,
    suggestedStartOffset: 20,
    dependencies: ['FIN-050'],
    acceptanceCriteria: ['Final grade drains away from home', 'Driveway/hardscape installed', 'Landscaping complete'],
    requiredPhotos: 5,
    requiredDocuments: [],
    inspectionRequired: false,
    drawMilestoneRelevant: false,
    clientVisible: true,
    subcontractorVisible: true,
    isRequired: true,
    tags: ['retaining wall', 'pool'],
    appliesWhen: 'Every custom home',
    riskLevel: 'medium',
    qualityGate: false,
  },
  {
    taskCode: 'FIN-070',
    phase: 'Finishes & Commissioning',
    title: 'Pool / spa construction',
    description: 'Construct in-ground pool/spa, equipment, and safety barriers per permit.',
    recommendedRole: 'subcontractor',
    defaultAssigneeRole: 'subcontractor',
    defaultDurationDays: 30,
    suggestedStartOffset: 0,
    dependencies: ['FRAME-010'],
    acceptanceCriteria: ['Pool shell & equipment complete', 'Safety barrier installed', 'Pool inspection passed'],
    requiredPhotos: 6,
    requiredDocuments: ['Pool permit'],
    inspectionRequired: true,
    drawMilestoneRelevant: false,
    clientVisible: true,
    subcontractorVisible: true,
    isRequired: false,
    tags: ['pool'],
    appliesWhen: 'Homes with a pool/spa',
    riskLevel: 'high',
    qualityGate: true,
  },
  {
    taskCode: 'FIN-080',
    phase: 'Finishes & Commissioning',
    title: 'Elevator installation & certification',
    description: 'Install and certify the residential elevator.',
    recommendedRole: 'subcontractor',
    defaultAssigneeRole: 'subcontractor',
    defaultDurationDays: 14,
    suggestedStartOffset: 10,
    dependencies: ['MEP-060'],
    acceptanceCriteria: ['Elevator installed', 'State certification passed'],
    requiredPhotos: 3,
    requiredDocuments: ['Elevator certification'],
    inspectionRequired: true,
    drawMilestoneRelevant: false,
    clientVisible: true,
    subcontractorVisible: true,
    isRequired: false,
    tags: ['elevator'],
    appliesWhen: 'Homes with an elevator',
    riskLevel: 'high',
    qualityGate: true,
  },
  {
    taskCode: 'FIN-090',
    phase: 'Finishes & Commissioning',
    title: 'Systems commissioning & client orientation',
    description:
      'Test and balance HVAC, verify all systems, and walk the client through home systems operation.',
    recommendedRole: 'superintendent',
    defaultAssigneeRole: 'superintendent',
    defaultDurationDays: 3,
    suggestedStartOffset: 30,
    dependencies: ['FIN-050'],
    acceptanceCriteria: ['HVAC tested & balanced', 'All systems verified', 'Client orientation completed'],
    requiredPhotos: 2,
    requiredDocuments: [],
    inspectionRequired: false,
    drawMilestoneRelevant: false,
    clientVisible: true,
    subcontractorVisible: false,
    isRequired: true,
    tags: ['smart home', 'solar'],
    appliesWhen: 'Every custom home',
    riskLevel: 'medium',
    qualityGate: true,
  },

  // ── Phase 8: Punchlist, Closeout & Warranty ───────────────────────────────
  {
    taskCode: 'CLOSE-010',
    phase: 'Punchlist, Closeout & Warranty',
    title: 'Final inspection & Certificate of Occupancy',
    description:
      'Pass the jurisdiction final inspection and obtain the Certificate of Occupancy.',
    recommendedRole: 'inspector',
    defaultAssigneeRole: 'superintendent',
    defaultDurationDays: 5,
    suggestedStartOffset: 0,
    dependencies: ['FIN-090'],
    acceptanceCriteria: ['Final inspection passed', 'Certificate of Occupancy issued'],
    requiredPhotos: 1,
    requiredDocuments: ['Certificate of Occupancy'],
    inspectionRequired: true,
    drawMilestoneRelevant: true,
    clientVisible: true,
    subcontractorVisible: false,
    isRequired: true,
    tags: [],
    appliesWhen: 'Every custom home',
    riskLevel: 'high',
    qualityGate: true,
  },
  {
    taskCode: 'CLOSE-020',
    phase: 'Punchlist, Closeout & Warranty',
    title: 'Client pre-closing walkthrough & punchlist',
    description:
      'Walk the home with the client to create the punchlist; track each item to completion.',
    recommendedRole: 'projectManager',
    defaultAssigneeRole: 'projectManager',
    defaultDurationDays: 10,
    suggestedStartOffset: 3,
    dependencies: ['CLOSE-010'],
    acceptanceCriteria: ['Walkthrough completed', 'Punchlist captured', 'All punch items closed'],
    requiredPhotos: 3,
    requiredDocuments: ['Signed punchlist'],
    inspectionRequired: false,
    drawMilestoneRelevant: false,
    clientVisible: true,
    subcontractorVisible: true,
    isRequired: true,
    tags: [],
    appliesWhen: 'Every custom home',
    riskLevel: 'medium',
    qualityGate: true,
  },
  {
    taskCode: 'CLOSE-030',
    phase: 'Punchlist, Closeout & Warranty',
    title: 'Final cleaning',
    description: 'Complete construction final clean before client move-in.',
    recommendedRole: 'subcontractor',
    defaultAssigneeRole: 'subcontractor',
    defaultDurationDays: 3,
    suggestedStartOffset: 10,
    dependencies: ['CLOSE-020'],
    acceptanceCriteria: ['Final clean complete', 'Windows & fixtures detailed'],
    requiredPhotos: 2,
    requiredDocuments: [],
    inspectionRequired: false,
    drawMilestoneRelevant: false,
    clientVisible: true,
    subcontractorVisible: true,
    isRequired: true,
    tags: [],
    appliesWhen: 'Every custom home',
    riskLevel: 'low',
    qualityGate: false,
  },
  {
    taskCode: 'CLOSE-040',
    phase: 'Punchlist, Closeout & Warranty',
    title: 'Closeout package & warranties (move-in binder)',
    description:
      'Assemble warranties, manuals, as-builts, and subcontractor info into the client move-in binder.',
    recommendedRole: 'projectManager',
    defaultAssigneeRole: 'projectManager',
    defaultDurationDays: 7,
    suggestedStartOffset: 7,
    dependencies: ['CLOSE-020'],
    acceptanceCriteria: ['Warranties collected', 'Manuals & as-builts compiled', 'Move-in binder delivered to client'],
    requiredPhotos: 1,
    requiredDocuments: ['Move-in binder'],
    inspectionRequired: false,
    drawMilestoneRelevant: false,
    clientVisible: true,
    subcontractorVisible: false,
    isRequired: true,
    tags: [],
    appliesWhen: 'Every custom home',
    riskLevel: 'medium',
    qualityGate: false,
  },
  {
    taskCode: 'CLOSE-050',
    phase: 'Punchlist, Closeout & Warranty',
    title: 'Final draw & financial closeout',
    description:
      'Submit the final draw, reconcile budget vs. actuals, release retainage, and close the job financially.',
    recommendedRole: 'gc',
    defaultAssigneeRole: 'gc',
    defaultDurationDays: 14,
    suggestedStartOffset: 10,
    dependencies: ['CLOSE-010'],
    acceptanceCriteria: ['Final draw submitted', 'Budget reconciled', 'Lien releases collected', 'Retainage released'],
    requiredPhotos: 0,
    requiredDocuments: ['Final draw package', 'Lien releases'],
    inspectionRequired: false,
    drawMilestoneRelevant: true,
    clientVisible: false,
    subcontractorVisible: false,
    isRequired: true,
    tags: [],
    appliesWhen: 'Every custom home',
    riskLevel: 'high',
    qualityGate: true,
  },
  {
    taskCode: 'CLOSE-060',
    phase: 'Punchlist, Closeout & Warranty',
    title: 'Establish warranty period & reminders',
    description:
      'Set the move-in date to trigger 3/6/11/12-month warranty reminders and confirm the warranty process with the client.',
    recommendedRole: 'projectManager',
    defaultAssigneeRole: 'projectManager',
    defaultDurationDays: 2,
    suggestedStartOffset: 10,
    dependencies: ['CLOSE-040'],
    acceptanceCriteria: ['Move-in date set', 'Warranty reminders scheduled', 'Warranty terms reviewed with client'],
    requiredPhotos: 0,
    requiredDocuments: [],
    inspectionRequired: false,
    drawMilestoneRelevant: false,
    clientVisible: true,
    subcontractorVisible: false,
    isRequired: true,
    tags: [],
    appliesWhen: 'Every custom home',
    riskLevel: 'low',
    qualityGate: false,
  },
  {
    taskCode: 'CLOSE-070',
    phase: 'Punchlist, Closeout & Warranty',
    title: 'Internal closeout lessons-learned review',
    description:
      'Run the Closeout Lessons Learned workflow: review custom/skipped/delayed/blocked tasks and promote improvements into the Master Task Library.',
    recommendedRole: 'admin',
    defaultAssigneeRole: 'admin',
    defaultDurationDays: 3,
    suggestedStartOffset: 14,
    dependencies: ['CLOSE-050'],
    acceptanceCriteria: ['Lessons-learned reviewed', 'Improvements promoted or dispositioned'],
    requiredPhotos: 0,
    requiredDocuments: [],
    inspectionRequired: false,
    drawMilestoneRelevant: false,
    clientVisible: false,
    subcontractorVisible: false,
    isRequired: true,
    tags: [],
    appliesWhen: 'Every custom home',
    riskLevel: 'low',
    qualityGate: false,
  },
];
