import { format, differenceInDays, addDays, startOfWeek, endOfWeek } from 'date-fns';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Edit, Trash2, User } from 'lucide-react';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from '@/components/ui/alert-dialog';

interface Task {
  id: number;
  title: string;
  trade: string;
  contactId?: number;
  startDate: string;
  endDate: string;
  duration: number;
  status: string;
  description?: string;
  notes?: string;
  isAutoGenerated: boolean;
}

interface GanttViewProps {
  tasks: Task[];
  onEditTask: (task: Task) => void;
  onDeleteTask: (taskId: number) => void;
}

export default function GanttView({ tasks, onEditTask, onDeleteTask }: GanttViewProps) {
  if (tasks.length === 0) {
    return (
      <div className="text-center py-12">
        <div className="text-gray-400 mb-4">
          <svg className="mx-auto h-12 w-12" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
          </svg>
        </div>
        <h3 className="text-lg font-medium text-gray-900 mb-2">No Tasks Scheduled</h3>
        <p className="text-gray-600 mb-4">
          Get started by adding a task manually or auto-generating from approved estimates.
        </p>
      </div>
    );
  }

  // Calculate timeline boundaries
  const startDates = tasks.map(task => new Date(task.startDate));
  const endDates = tasks.map(task => new Date(task.endDate));
  const minDate = new Date(Math.min(...startDates.map(d => d.getTime())));
  const maxDate = new Date(Math.max(...endDates.map(d => d.getTime())));
  
  // Extend timeline to show full weeks
  const timelineStart = startOfWeek(minDate);
  const timelineEnd = endOfWeek(maxDate);
  const totalDays = differenceInDays(timelineEnd, timelineStart) + 1;

  // Generate timeline headers (weeks)
  const timelineWeeks = [];
  let currentWeek = timelineStart;
  while (currentWeek <= timelineEnd) {
    timelineWeeks.push(new Date(currentWeek));
    currentWeek = addDays(currentWeek, 7);
  }

  const getStatusColor = (status: string) => {
    switch (status.toLowerCase()) {
      case 'scheduled':
        return 'bg-blue-100 text-blue-800';
      case 'in progress':
        return 'bg-yellow-100 text-yellow-800';
      case 'complete':
        return 'bg-green-100 text-green-800';
      case 'cancelled':
        return 'bg-red-100 text-red-800';
      default:
        return 'bg-gray-100 text-gray-800';
    }
  };

  const getTaskPosition = (task: Task) => {
    const taskStart = new Date(task.startDate);
    const taskEnd = new Date(task.endDate);
    const startOffset = differenceInDays(taskStart, timelineStart);
    const taskDuration = differenceInDays(taskEnd, taskStart) + 1;
    
    return {
      left: `${(startOffset / totalDays) * 100}%`,
      width: `${(taskDuration / totalDays) * 100}%`,
    };
  };

  return (
    <div className="space-y-4">
      {/* Timeline Header */}
      <Card className="bg-gray-50">
        <CardContent className="p-4">
          <div className="flex text-xs text-gray-600 border-b border-gray-200 pb-2">
            <div className="w-80 flex-shrink-0 pr-4">
              <strong>Task / Trade</strong>
            </div>
            <div className="flex-1 relative">
              <div className="flex">
                {timelineWeeks.map((week, index) => (
                  <div 
                    key={index} 
                    className="flex-1 text-center border-l border-gray-200 px-2"
                  >
                    {format(week, 'MMM d')}
                  </div>
                ))}
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Task Rows */}
      <div className="space-y-2">
        {tasks.map((task) => (
          <Card key={task.id} className="overflow-hidden">
            <CardContent className="p-4">
              <div className="flex items-center">
                {/* Task Info */}
                <div className="w-80 flex-shrink-0 pr-4">
                  <div className="flex items-center justify-between">
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-1">
                        <h4 className="font-medium text-gray-900 truncate">
                          {task.title}
                        </h4>
                        {task.isAutoGenerated && (
                          <Badge variant="outline" className="text-xs">Auto</Badge>
                        )}
                      </div>
                      <div className="flex items-center gap-2 text-sm text-gray-600">
                        <span className="font-medium">{task.trade}</span>
                        {task.contactId && (
                          <span className="flex items-center gap-1">
                            <User className="h-3 w-3" />
                            Sub #{task.contactId}
                          </span>
                        )}
                      </div>
                      <div className="mt-1">
                        <Badge className={getStatusColor(task.status)} variant="secondary">
                          {task.status}
                        </Badge>
                      </div>
                    </div>
                    <div className="flex gap-1 ml-2">
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => onEditTask(task)}
                        className="h-8 w-8 p-0"
                      >
                        <Edit className="h-3 w-3" />
                      </Button>
                      <AlertDialog>
                        <AlertDialogTrigger asChild>
                          <Button
                            variant="ghost"
                            size="sm"
                            className="h-8 w-8 p-0 text-red-600 hover:text-red-700"
                          >
                            <Trash2 className="h-3 w-3" />
                          </Button>
                        </AlertDialogTrigger>
                        <AlertDialogContent>
                          <AlertDialogHeader>
                            <AlertDialogTitle>Delete Task</AlertDialogTitle>
                            <AlertDialogDescription>
                              Are you sure you want to delete "{task.title}"? This action cannot be undone.
                            </AlertDialogDescription>
                          </AlertDialogHeader>
                          <AlertDialogFooter>
                            <AlertDialogCancel>Cancel</AlertDialogCancel>
                            <AlertDialogAction
                              onClick={() => onDeleteTask(task.id)}
                              className="bg-red-600 hover:bg-red-700"
                            >
                              Delete
                            </AlertDialogAction>
                          </AlertDialogFooter>
                        </AlertDialogContent>
                      </AlertDialog>
                    </div>
                  </div>
                </div>

                {/* Timeline Bar */}
                <div className="flex-1 relative h-8">
                  <div className="absolute inset-0 bg-gray-100 rounded"></div>
                  <div
                    className="absolute top-1 bottom-1 bg-blue-500 rounded shadow-sm flex items-center px-2"
                    style={getTaskPosition(task)}
                  >
                    <span className="text-white text-xs font-medium truncate">
                      {task.duration} day{task.duration !== 1 ? 's' : ''}
                    </span>
                  </div>
                </div>
              </div>
              
              {/* Task Details */}
              <div className="mt-3 pt-3 border-t border-gray-200">
                <div className="grid grid-cols-2 gap-4 text-sm">
                  <div>
                    <span className="text-gray-600">Start: </span>
                    <span className="font-medium">{format(new Date(task.startDate), 'MMM d, yyyy')}</span>
                  </div>
                  <div>
                    <span className="text-gray-600">End: </span>
                    <span className="font-medium">{format(new Date(task.endDate), 'MMM d, yyyy')}</span>
                  </div>
                </div>
                {task.description && (
                  <p className="text-sm text-gray-600 mt-2">{task.description}</p>
                )}
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}