import { db } from '../db';
import { projectTasks, scheduleSections, taskDependencies } from '@shared/schema';
import { eq, and, desc } from 'drizzle-orm';
import { v4 as uuidv4 } from 'uuid';
import type { ProjectTask, InsertProjectTask, ScheduleSection, InsertScheduleSection } from '@shared/schema';

export interface ScheduleTaskCreate {
  projectId: number;
  title: string;
  trade: string;
  startDate: Date;
  endDate: Date;
  duration: number;
  description?: string;
  contactId?: number;
  sectionId?: number;
  dependsOn?: number[];
}

export interface ScheduleDependencyCreate {
  projectId: number;
  fromTaskId: number;
  toTaskId: number;
  dependencyType?: 'FS' | 'SS' | 'FF' | 'SF';
  lagDays?: number;
}

export const ScheduleService = {
  // Task Management
  async createTask(taskData: ScheduleTaskCreate): Promise<ProjectTask> {
    const insertData: InsertProjectTask = {
      projectId: taskData.projectId,
      title: taskData.title,
      trade: taskData.trade,
      startDate: taskData.startDate,
      endDate: taskData.endDate,
      duration: taskData.duration,
      description: taskData.description,
      contactId: taskData.contactId,
      sectionId: taskData.sectionId,
      dependsOn: taskData.dependsOn ? JSON.stringify(taskData.dependsOn) : null,
      status: 'Scheduled',
      isAutoGenerated: false,
    };

    const [task] = await db
      .insert(projectTasks)
      .values(insertData)
      .returning();
    
    return task;
  },

  async getTasks(projectId: number): Promise<ProjectTask[]> {
    return await db
      .select()
      .from(projectTasks)
      .where(eq(projectTasks.projectId, projectId))
      .orderBy(desc(projectTasks.orderIndex));
  },

  async getTask(id: number): Promise<ProjectTask | undefined> {
    const [task] = await db
      .select()
      .from(projectTasks)
      .where(eq(projectTasks.id, id));
    return task || undefined;
  },

  async updateTask(id: number, updates: Partial<ProjectTask>): Promise<ProjectTask | undefined> {
    const [updatedTask] = await db
      .update(projectTasks)
      .set({
        ...updates,
        updatedAt: new Date(),
      })
      .where(eq(projectTasks.id, id))
      .returning();
    
    return updatedTask || undefined;
  },

  async updateTaskDates(id: number, startDate: Date, endDate: Date): Promise<ProjectTask | undefined> {
    const duration = Math.ceil((endDate.getTime() - startDate.getTime()) / (1000 * 60 * 60 * 24));
    
    return await this.updateTask(id, {
      startDate,
      endDate,
      duration,
    });
  },

  async deleteTask(id: number): Promise<boolean> {
    try {
      await db.delete(projectTasks).where(eq(projectTasks.id, id));
      return true;
    } catch (error) {
      console.error('Error deleting task:', error);
      return false;
    }
  },

  // Section Management
  async createSection(sectionData: Omit<InsertScheduleSection, 'id'>): Promise<ScheduleSection> {
    const [section] = await db
      .insert(scheduleSections)
      .values(sectionData)
      .returning();
    
    return section;
  },

  async getSections(projectId: number): Promise<ScheduleSection[]> {
    return await db
      .select()
      .from(scheduleSections)
      .where(eq(scheduleSections.projectId, projectId))
      .orderBy(desc(scheduleSections.orderIndex));
  },

  async updateSection(id: number, updates: Partial<ScheduleSection>): Promise<ScheduleSection | undefined> {
    const [updatedSection] = await db
      .update(scheduleSections)
      .set({
        ...updates,
        updatedAt: new Date(),
      })
      .where(eq(scheduleSections.id, id))
      .returning();
    
    return updatedSection || undefined;
  },

  async deleteSection(id: number): Promise<boolean> {
    try {
      // First, remove section reference from tasks
      await db
        .update(projectTasks)
        .set({ sectionId: null })
        .where(eq(projectTasks.sectionId, id));
      
      // Then delete the section
      await db.delete(scheduleSections).where(eq(scheduleSections.id, id));
      return true;
    } catch (error) {
      console.error('Error deleting section:', error);
      return false;
    }
  },

  // Dependency Management
  async createDependency(depData: ScheduleDependencyCreate): Promise<any> {
    const [dependency] = await db
      .insert(taskDependencies)
      .values({
        projectId: depData.projectId,
        fromTaskId: depData.fromTaskId,
        toTaskId: depData.toTaskId,
        dependencyType: depData.dependencyType || 'FS',
        lagDays: depData.lagDays || 0,
      })
      .returning();
    
    return dependency;
  },

  async getDependencies(projectId: number): Promise<any[]> {
    return await db
      .select()
      .from(taskDependencies)
      .where(eq(taskDependencies.projectId, projectId));
  },

  async deleteDependency(id: number): Promise<boolean> {
    try {
      await db.delete(taskDependencies).where(eq(taskDependencies.id, id));
      return true;
    } catch (error) {
      console.error('Error deleting dependency:', error);
      return false;
    }
  },

  // Complete Project Schedule
  async getProjectSchedule(projectId: number): Promise<{
    tasks: ProjectTask[];
    sections: ScheduleSection[];
    dependencies: any[];
  }> {
    const [tasks, sections, dependencies] = await Promise.all([
      this.getTasks(projectId),
      this.getSections(projectId),
      this.getDependencies(projectId),
    ]);

    return { tasks, sections, dependencies };
  },

  // Auto-scheduling utilities
  async calculateTaskDuration(startDate: Date, endDate: Date): Promise<number> {
    return Math.ceil((endDate.getTime() - startDate.getTime()) / (1000 * 60 * 60 * 24));
  },

  async validateTaskDates(projectId: number, taskId: number, startDate: Date, endDate: Date): Promise<{
    valid: boolean;
    conflicts: string[];
  }> {
    const conflicts: string[] = [];
    
    // Check for dependency conflicts
    const dependencies = await db
      .select()
      .from(taskDependencies)
      .where(
        and(
          eq(taskDependencies.projectId, projectId),
          eq(taskDependencies.toTaskId, taskId)
        )
      );

    for (const dep of dependencies) {
      const [predecessorTask] = await db
        .select()
        .from(projectTasks)
        .where(eq(projectTasks.id, dep.fromTaskId));

      if (predecessorTask && dep.dependencyType === 'FS') {
        const minStartDate = new Date(predecessorTask.endDate);
        if (dep.lagDays) {
          minStartDate.setDate(minStartDate.getDate() + dep.lagDays);
        }
        
        if (startDate < minStartDate) {
          conflicts.push(`Task cannot start before ${minStartDate.toDateString()} due to dependency on "${predecessorTask.title}"`);
        }
      }
    }

    return {
      valid: conflicts.length === 0,
      conflicts,
    };
  },

  // Bulk operations for schedule generation
  async createTasksBulk(projectId: number, tasks: ScheduleTaskCreate[]): Promise<ProjectTask[]> {
    const created: ProjectTask[] = [];
    
    for (const taskData of tasks) {
      const task = await this.createTask(taskData);
      created.push(task);
    }
    
    return created;
  },
};

export default ScheduleService;