import React, { useState, useEffect } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { useToast } from '@/hooks/use-toast';
import { apiRequest } from '@/lib/queryClient';
import { CheckCircle, Clock, DollarSign, FileText, Play, AlertCircle, Calculator, Receipt, Settings } from 'lucide-react';

interface Invoice {
  id: number;
  invoiceId: string;
  projectId: number;
  contactId: number;
  poId?: number;
  invoiceNumber: string;
  description: string;
  amount: number;
  trade: string;
  status: string;
  isAutoGenerated: boolean;
  linkedJobId?: number;
  totalPaid: number;
  remainingBalance: number;
  submittedDate: string;
  dueDate: string;
  notes?: string;
}

interface PurchaseOrder {
  id: number;
  poNumber: string;
  projectId: number;
  contactId: number;
  trade: string;
  amount: number;
  status: string;
  linkedJobId?: number;
}

interface PaymentData {
  amount: string;
  paymentDate: string;
  paymentMethod: string;
  checkNumber?: string;
  referenceNumber?: string;
  notes?: string;
}

const AutomatedInvoiceManagement: React.FC<{ projectId: number }> = ({ projectId }) => {
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const [selectedInvoice, setSelectedInvoice] = useState<Invoice | null>(null);
  const [paymentData, setPaymentData] = useState<PaymentData>({
    amount: '',
    paymentDate: new Date().toISOString().split('T')[0],
    paymentMethod: 'Bank Transfer',
    checkNumber: '',
    referenceNumber: '',
    notes: ''
  });

  // Fetch invoices for the project
  const { data: invoices, isLoading: invoicesLoading } = useQuery({
    queryKey: ['/api/invoices/project', projectId],
    enabled: !!projectId
  });

  // Fetch purchase orders for the project
  const { data: purchaseOrders, isLoading: posLoading } = useQuery({
    queryKey: ['/api/purchase-orders/project', projectId],
    enabled: !!projectId
  });

  // Auto-generate invoice from PO
  const generateInvoiceMutation = useMutation({
    mutationFn: async ({ poId, linkedJobId }: { poId: number; linkedJobId?: number }) => {
      return await apiRequest('POST', `/api/purchase-orders/${poId}/generate-invoice`, {
        linkedJobId
      });
    },
    onSuccess: (data) => {
      toast({
        title: "Invoice Auto-Generated",
        description: `${data.message}`,
        variant: "default"
      });
      queryClient.invalidateQueries({ queryKey: ['/api/invoices/project', projectId] });
    },
    onError: (error: any) => {
      toast({
        title: "Invoice Generation Failed",
        description: error.message || "Unable to generate invoice from Purchase Order",
        variant: "destructive"
      });
    }
  });

  // Manual check for auto-invoice creation (NEW)
  const checkAutoInvoiceMutation = useMutation({
    mutationFn: async (poId: number) => {
      return await apiRequest('POST', `/api/auto-invoice/check/${poId}`);
    },
    onSuccess: (data) => {
      toast({
        title: data.autoInvoiceCreated ? "Auto-Invoice Created!" : "No Auto-Invoice Created", 
        description: data.message,
        variant: data.autoInvoiceCreated ? "default" : "destructive",
      });
      queryClient.invalidateQueries({ queryKey: ['/api/invoices/project', projectId] });
    },
    onError: (error: any) => {
      toast({
        title: "Auto-Invoice Check Failed",
        description: error.message || "Failed to check auto-invoice creation.",
        variant: "destructive",
      });
    }
  });

  // Record payment
  const recordPaymentMutation = useMutation({
    mutationFn: async ({ invoiceId, paymentData }: { invoiceId: number; paymentData: PaymentData }) => {
      return await apiRequest('POST', `/api/invoices/${invoiceId}/record-payment`, paymentData);
    },
    onSuccess: (data) => {
      toast({
        title: "Payment Recorded",
        description: `${data.message}`,
        variant: "default"
      });
      queryClient.invalidateQueries({ queryKey: ['/api/invoices/project', projectId] });
      setSelectedInvoice(null);
      setPaymentData({
        amount: '',
        paymentDate: new Date().toISOString().split('T')[0],
        paymentMethod: 'Bank Transfer',
        checkNumber: '',
        referenceNumber: '',
        notes: ''
      });
    },
    onError: (error: any) => {
      toast({
        title: "Payment Recording Failed",
        description: error.message || "Unable to record payment",
        variant: "destructive"
      });
    }
  });

  // Approve invoice for payment
  const approveInvoiceMutation = useMutation({
    mutationFn: async (invoiceId: number) => {
      return await apiRequest('POST', `/api/invoices/${invoiceId}/approve-for-payment`, {
        approvedBy: 1 // Current user ID
      });
    },
    onSuccess: (data) => {
      toast({
        title: "Invoice Approved",
        description: "Invoice has been approved for payment",
        variant: "default"
      });
      queryClient.invalidateQueries({ queryKey: ['/api/invoices/project', projectId] });
    },
    onError: (error: any) => {
      toast({
        title: "Approval Failed",
        description: error.message || "Unable to approve invoice",
        variant: "destructive"
      });
    }
  });

  const getStatusBadge = (status: string) => {
    const variants: Record<string, "default" | "secondary" | "destructive" | "outline"> = {
      'pending_approval': 'secondary',
      'approved': 'default',
      'partial_paid': 'outline',
      'paid_in_full': 'default'
    };

    const colors = {
      'pending_approval': 'bg-amber-500',
      'approved': 'bg-emerald-500', 
      'partial_paid': 'bg-blue-500',
      'paid_in_full': 'bg-green-600'
    };

    return (
      <Badge variant={variants[status] || 'outline'} className={colors[status]}>
        {status.replace('_', ' ').toUpperCase()}
      </Badge>
    );
  };

  const getPOStatusBadge = (status: string) => {
    const colors = {
      'draft': 'bg-gray-500',
      'sent': 'bg-blue-500',
      'signed': 'bg-green-500',
      'completed': 'bg-emerald-600'
    };

    return (
      <Badge className={colors[status]}>
        {status.toUpperCase()}
      </Badge>
    );
  };

  if (invoicesLoading || posLoading) {
    return (
      <div className="flex items-center justify-center p-8">
        <div className="animate-spin w-8 h-8 border-4 border-primary border-t-transparent rounded-full" />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold">Automated Invoice Management</h2>
          <p className="text-muted-foreground">
            Manage invoices with automated creation from Purchase Orders and multi-payment tracking
          </p>
        </div>
      </div>

      {/* Auto-Invoice Testing Section */}
      {purchaseOrders && purchaseOrders.length > 0 && (
        <Card className="border-2 border-green-200 bg-green-50/30">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-green-700">
              <CheckCircle className="h-5 w-5" />
              Automatic Invoice Creation Testing
            </CardTitle>
            <CardDescription className="text-green-600">
              Test the new automated invoice creation system triggered by Purchase Order signing and task completion
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              <div className="p-4 bg-white rounded-lg border">
                <h4 className="font-semibold mb-2 flex items-center gap-2">
                  <Settings className="h-4 w-4" />
                  How It Works
                </h4>
                <ul className="text-sm space-y-1 text-muted-foreground">
                  <li>• When a subcontractor signs a Purchase Order, the system automatically checks if related work is completed</li>
                  <li>• If matching completed tasks exist, an invoice is automatically generated</li>
                  <li>• Auto-generated invoices are marked with the green "Auto-Generated" badge</li>
                  <li>• Click "Test Auto-Invoice" to manually trigger the check for any signed PO</li>
                </ul>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                {purchaseOrders
                  .filter((po: PurchaseOrder) => po.status === 'signed')
                  .map((po: PurchaseOrder) => (
                  <Card key={po.id} className="border border-green-200">
                    <CardContent className="p-4">
                      <div className="flex items-center justify-between mb-3">
                        <div className="font-semibold text-green-700">PO #{po.poNumber}</div>
                        <Badge className="bg-green-500 text-white">SIGNED</Badge>
                      </div>
                      
                      <div className="space-y-2 text-sm text-muted-foreground">
                        <div className="flex justify-between">
                          <span>Trade:</span>
                          <span className="font-medium text-foreground">{po.trade}</span>
                        </div>
                        <div className="flex justify-between">
                          <span>Amount:</span>
                          <span className="font-medium text-foreground">${po.amount.toLocaleString()}</span>
                        </div>
                        <div className="flex justify-between">
                          <span>Status:</span>
                          <span className="font-medium text-green-600">Ready for Auto-Invoice</span>
                        </div>
                      </div>

                      <Button
                        className="w-full mt-4 bg-green-600 hover:bg-green-700"
                        onClick={() => checkAutoInvoiceMutation.mutate(po.id)}
                        disabled={checkAutoInvoiceMutation.isPending}
                      >
                        <Calculator className="h-4 w-4 mr-2" />
                        Test Auto-Invoice
                      </Button>
                    </CardContent>
                  </Card>
                ))}
              </div>

              {purchaseOrders.filter((po: PurchaseOrder) => po.status === 'signed').length === 0 && (
                <div className="text-center py-6 text-green-600">
                  <AlertCircle className="h-8 w-8 mx-auto mb-3 opacity-60" />
                  <p>No signed Purchase Orders available for auto-invoice testing</p>
                  <p className="text-sm mt-1 opacity-75">Sign a PO in the subcontractor portal to test this feature</p>
                </div>
              )}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Purchase Orders Ready for Invoice Generation */}
      {purchaseOrders && purchaseOrders.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Settings className="h-5 w-5" />
              Purchase Orders - Invoice Generation
            </CardTitle>
            <CardDescription>
              Signed Purchase Orders that can automatically generate invoices
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {purchaseOrders
                .filter((po: PurchaseOrder) => po.status === 'signed')
                .map((po: PurchaseOrder) => (
                <Card key={po.id} className="border-2 border-dashed border-blue-200">
                  <CardContent className="p-4">
                    <div className="flex items-center justify-between mb-3">
                      <div className="font-semibold">PO #{po.poNumber}</div>
                      {getPOStatusBadge(po.status)}
                    </div>
                    
                    <div className="space-y-2 text-sm text-muted-foreground">
                      <div className="flex justify-between">
                        <span>Trade:</span>
                        <span className="font-medium text-foreground">{po.trade}</span>
                      </div>
                      <div className="flex justify-between">
                        <span>Amount:</span>
                        <span className="font-medium text-foreground">${po.amount.toLocaleString()}</span>
                      </div>
                    </div>

                    <Button
                      className="w-full mt-4"
                      onClick={() => generateInvoiceMutation.mutate({ poId: po.id, linkedJobId: po.linkedJobId })}
                      disabled={generateInvoiceMutation.isPending}
                    >
                      <Play className="h-4 w-4 mr-2" />
                      Auto-Generate Invoice
                    </Button>
                  </CardContent>
                </Card>
              ))}
            </div>

            {purchaseOrders.filter((po: PurchaseOrder) => po.status === 'signed').length === 0 && (
              <div className="text-center py-8 text-muted-foreground">
                <Settings className="h-12 w-12 mx-auto mb-4 opacity-50" />
                <p>No signed Purchase Orders available for invoice generation</p>
              </div>
            )}
          </CardContent>
        </Card>
      )}

      {/* Existing Invoices */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5" />
            Project Invoices
          </CardTitle>
          <CardDescription>
            All invoices for this project with payment tracking
          </CardDescription>
        </CardHeader>
        <CardContent>
          {invoices && invoices.length > 0 ? (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {invoices.map((invoice: Invoice) => (
                <Card key={invoice.id} className={`${invoice.isAutoGenerated ? 'border-green-200 bg-green-50/50' : ''}`}>
                  <CardContent className="p-4">
                    <div className="flex items-center justify-between mb-3">
                      <div className="font-semibold">{invoice.invoiceNumber}</div>
                      {getStatusBadge(invoice.status)}
                    </div>

                    {invoice.isAutoGenerated && (
                      <div className="flex items-center gap-1 mb-2 text-xs text-green-600">
                        <CheckCircle className="h-3 w-3" />
                        Auto-Generated
                      </div>
                    )}
                    
                    <div className="space-y-2 text-sm text-muted-foreground">
                      <div className="flex justify-between">
                        <span>Trade:</span>
                        <span className="font-medium text-foreground">{invoice.trade}</span>
                      </div>
                      <div className="flex justify-between">
                        <span>Amount:</span>
                        <span className="font-medium text-foreground">${invoice.amount.toLocaleString()}</span>
                      </div>
                      <div className="flex justify-between">
                        <span>Paid:</span>
                        <span className="font-medium text-green-600">${(invoice.totalPaid || 0).toLocaleString()}</span>
                      </div>
                      <div className="flex justify-between">
                        <span>Balance:</span>
                        <span className="font-medium text-orange-600">
                          ${((invoice.remainingBalance || invoice.amount) - (invoice.totalPaid || 0)).toLocaleString()}
                        </span>
                      </div>
                      <div className="flex justify-between">
                        <span>Due:</span>
                        <span className="font-medium text-foreground">
                          {new Date(invoice.dueDate).toLocaleDateString()}
                        </span>
                      </div>
                    </div>

                    <div className="flex gap-2 mt-4">
                      {invoice.status === 'pending_approval' && (
                        <Button
                          size="sm"
                          onClick={() => approveInvoiceMutation.mutate(invoice.id)}
                          disabled={approveInvoiceMutation.isPending}
                          className="flex-1"
                        >
                          <CheckCircle className="h-3 w-3 mr-1" />
                          Approve
                        </Button>
                      )}

                      {(invoice.status === 'approved' || invoice.status === 'partial_paid') && (
                        <Dialog>
                          <DialogTrigger asChild>
                            <Button 
                              size="sm" 
                              variant="outline" 
                              className="flex-1"
                              onClick={() => setSelectedInvoice(invoice)}
                            >
                              <DollarSign className="h-3 w-3 mr-1" />
                              Pay
                            </Button>
                          </DialogTrigger>
                          <DialogContent className="max-w-md">
                            <DialogHeader>
                              <DialogTitle>Record Payment</DialogTitle>
                              <DialogDescription>
                                Record a payment for invoice {selectedInvoice?.invoiceNumber}
                              </DialogDescription>
                            </DialogHeader>

                            <div className="space-y-4 py-4">
                              <div className="grid grid-cols-2 gap-4">
                                <div>
                                  <Label>Amount</Label>
                                  <Input
                                    type="number"
                                    step="0.01"
                                    value={paymentData.amount}
                                    onChange={(e) => setPaymentData(prev => ({ ...prev, amount: e.target.value }))}
                                    placeholder="0.00"
                                  />
                                </div>
                                <div>
                                  <Label>Payment Date</Label>
                                  <Input
                                    type="date"
                                    value={paymentData.paymentDate}
                                    onChange={(e) => setPaymentData(prev => ({ ...prev, paymentDate: e.target.value }))}
                                  />
                                </div>
                              </div>

                              <div>
                                <Label>Payment Method</Label>
                                <Select 
                                  value={paymentData.paymentMethod} 
                                  onValueChange={(value) => setPaymentData(prev => ({ ...prev, paymentMethod: value }))}
                                >
                                  <SelectTrigger>
                                    <SelectValue />
                                  </SelectTrigger>
                                  <SelectContent>
                                    <SelectItem value="Bank Transfer">Bank Transfer</SelectItem>
                                    <SelectItem value="Check">Check</SelectItem>
                                    <SelectItem value="ACH">ACH</SelectItem>
                                    <SelectItem value="Wire">Wire Transfer</SelectItem>
                                    <SelectItem value="Cash">Cash</SelectItem>
                                  </SelectContent>
                                </Select>
                              </div>

                              {paymentData.paymentMethod === 'Check' && (
                                <div>
                                  <Label>Check Number</Label>
                                  <Input
                                    value={paymentData.checkNumber}
                                    onChange={(e) => setPaymentData(prev => ({ ...prev, checkNumber: e.target.value }))}
                                    placeholder="Check number"
                                  />
                                </div>
                              )}

                              <div>
                                <Label>Reference Number (Optional)</Label>
                                <Input
                                  value={paymentData.referenceNumber}
                                  onChange={(e) => setPaymentData(prev => ({ ...prev, referenceNumber: e.target.value }))}
                                  placeholder="Reference or confirmation number"
                                />
                              </div>

                              <div>
                                <Label>Notes (Optional)</Label>
                                <Textarea
                                  value={paymentData.notes}
                                  onChange={(e) => setPaymentData(prev => ({ ...prev, notes: e.target.value }))}
                                  placeholder="Payment notes..."
                                  rows={2}
                                />
                              </div>

                              <Button
                                className="w-full"
                                onClick={() => selectedInvoice && recordPaymentMutation.mutate({ 
                                  invoiceId: selectedInvoice.id, 
                                  paymentData 
                                })}
                                disabled={!paymentData.amount || !paymentData.paymentMethod || recordPaymentMutation.isPending}
                              >
                                <Receipt className="h-4 w-4 mr-2" />
                                Record Payment
                              </Button>
                            </div>
                          </DialogContent>
                        </Dialog>
                      )}
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          ) : (
            <div className="text-center py-8 text-muted-foreground">
              <FileText className="h-12 w-12 mx-auto mb-4 opacity-50" />
              <p>No invoices found for this project</p>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
};

export default AutomatedInvoiceManagement;